spring.datasource.url=jdbc:postgresql://159.198.40.207:5432/escuelajuridica_pg
spring.datasource.username=escuelajuridica_pguser
spring.datasource.password=79RwTpm0yGKDusoFROpG6bZQdDrSwg3I

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
